name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Build serverSide
        run: make install
      - name: SET ENV Server
        run: |
          cd ./build
          touch .env
          echo ${{ secrets.HOST }} >> .env
          echo ${{ secrets.APP_KEY }} >> .env
          echo ${{ secrets.CACHE_VIEW }} >> .env
          echo ${{ secrets.DB_CONNECTION }} >> .env
          echo ${{ secrets.MYSQL_DB_NAME }} >> .env
          echo ${{ secrets.MYSQL_HOST }} >> .env
          echo ${{ secrets.MYSQL_PASSWORD }} >> .env
          echo ${{ secrets.MYSQL_PORT }} >> .env
          echo ${{ secrets.MYSQL_USER }} >> .env
          echo ${{ secrets.NODE_ENV }} >> .env
          echo ${{ secrets.PORT }} >> .env
          echo ${{ secrets.SESSION_DRIVER }} >> .env
  deploy:
    runs-on: self-hosted
    needs: build
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Déploiement DB
        run: make deployDB
      - name: Redémarrage PM2
        run: make restartApi
